# Generated by Django 5.2.1 on 2025-05-28 06:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CivilRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='أدخل الاسم الرباعي', max_length=100, verbose_name='الاسم')),
                ('national_id', models.CharField(help_text='أدخل رقم الهوية (9 أرقام)', max_length=9, unique=True, validators=[django.core.validators.RegexValidator(message='رقم الهوية يجب أن يكون 9 أرقام', regex='^\\d{9}$')], verbose_name='رقم الهوية')),
                ('gender', models.CharField(choices=[('M', 'ذكر'), ('F', 'أنثى')], max_length=1, verbose_name='الجنس')),
                ('birth_date', models.DateField(verbose_name='تاريخ الميلاد')),
                ('governorate', models.CharField(choices=[('gaza', 'غزة'), ('north_gaza', 'شمال غزة'), ('middle_area', 'الوسطى'), ('khan_younis', 'خان يونس'), ('rafah', 'رفح'), ('west_bank', 'الضفة الغربية'), ('jerusalem', 'القدس'), ('other', 'أخرى')], max_length=20, verbose_name='المحافظة')),
                ('city', models.CharField(max_length=50, verbose_name='المدينة')),
                ('family_members_count', models.PositiveIntegerField(default=1, help_text='العدد الإجمالي لأفراد الأسرة', verbose_name='عدد أفراد الأسرة')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'سجل مدني',
                'verbose_name_plural': 'السجل المدني',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['national_id'], name='civil_regis_nationa_07b629_idx'), models.Index(fields=['name'], name='civil_regis_name_d8d1c6_idx'), models.Index(fields=['governorate'], name='civil_regis_governo_a2d16e_idx')],
            },
        ),
    ]
