# Generated by Django 5.2.1 on 2025-05-28 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civil_registry', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='civilregistry',
            name='family_members_count',
        ),
        migrations.AddField(
            model_name='civilregistry',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='العنوان التفصيلي'),
        ),
        migrations.AddField(
            model_name='civilregistry',
            name='neighborhood',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='الحي'),
        ),
    ]
