# Generated by Django 5.2.1 on 2025-05-30 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civil_registry', '0002_remove_civilregistry_family_members_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='civilregistry',
            name='family_members_count',
            field=models.PositiveIntegerField(blank=True, help_text='أدخل العدد الإجمالي لأفراد الأسرة', null=True, verbose_name='عدد أفراد الأسرة'),
        ),
    ]
