# Generated by Django 5.2.1 on 2025-06-06 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civil_registry', '0003_civilregistry_family_members_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='civilregistry',
            name='family_members_count',
        ),
        migrations.AlterField(
            model_name='civilregistry',
            name='gender',
            field=models.CharField(choices=[('ذكر', 'ذكر'), ('أنثى', 'أنثى')], max_length=10, verbose_name='الجنس'),
        ),
    ]
