# Generated by Django 5.2.1 on 2025-05-28 06:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='أدخل اسم الحي', max_length=100, verbose_name='اسم الحي')),
                ('representative_name', models.CharField(help_text='أدخل اسم مندوب الحي', max_length=100, verbose_name='اسم مندوب الحي')),
                ('representative_id', models.CharField(help_text='أدخل رقم هوية مندوب الحي (9 أرقام)', max_length=9, validators=[django.core.validators.RegexValidator(message='رقم الهوية يجب أن يكون 9 أرقام', regex='^\\d{9}$')], verbose_name='رقم هوية مندوب الحي')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'حي',
                'verbose_name_plural': 'المناطق والأحياء',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='أدخل الاسم الرباعي', max_length=100, verbose_name='اسم ولي الأمر')),
                ('national_id', models.CharField(help_text='أدخل رقم الهوية (9 أرقام)', max_length=9, unique=True, validators=[django.core.validators.RegexValidator(message='رقم الهوية يجب أن يكون 9 أرقام', regex='^\\d{9}$')], verbose_name='رقم هوية ولي الأمر')),
                ('current_job', models.CharField(blank=True, max_length=100, null=True, verbose_name='الوظيفة الحالية')),
                ('phone_number', models.CharField(help_text='مثال: 0599123456', max_length=15, validators=[django.core.validators.RegexValidator(message='رقم الجوال غير صحيح', regex='^(\\+970|0)?5[0-9]{8}$')], verbose_name='رقم الجوال')),
                ('gender', models.CharField(choices=[('M', 'ذكر'), ('F', 'أنثى')], max_length=1, verbose_name='الجنس')),
                ('children_count', models.PositiveIntegerField(default=0, verbose_name='عدد الأبناء')),
                ('marital_status', models.CharField(choices=[('married', 'متزوج'), ('widowed', 'أرمل'), ('divorced', 'مطلق'), ('single', 'أعزب')], max_length=10, verbose_name='الحالة الاجتماعية')),
                ('wives_count', models.PositiveIntegerField(default=0, verbose_name='عدد الزوجات')),
                ('family_members_count', models.PositiveIntegerField(default=1, help_text='يحسب تلقائياً', verbose_name='عدد أفراد العائلة')),
                ('residence_status', models.CharField(choices=[('displaced', 'نازح'), ('resident', 'مقيم')], max_length=10, verbose_name='حالة الإقامة')),
                ('original_governorate', models.CharField(blank=True, max_length=50, null=True, verbose_name='المحافظة الأصلية')),
                ('original_city', models.CharField(blank=True, max_length=50, null=True, verbose_name='المدينة')),
                ('displacement_address', models.TextField(blank=True, null=True, verbose_name='عنوان النزوح')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='basic_data.district', verbose_name='الحي')),
            ],
            options={
                'verbose_name': 'ولي أمر',
                'verbose_name_plural': 'أولياء الأمور',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الابن/الابنة')),
                ('national_id', models.CharField(blank=True, max_length=9, null=True, validators=[django.core.validators.RegexValidator(message='رقم الهوية يجب أن يكون 9 أرقام', regex='^\\d{9}$')], verbose_name='رقم الهوية')),
                ('birth_date', models.DateField(verbose_name='تاريخ الميلاد')),
                ('gender', models.CharField(choices=[('M', 'ذكر'), ('F', 'أنثى')], max_length=1, verbose_name='الجنس')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('guardian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='basic_data.guardian', verbose_name='ولي الأمر')),
            ],
            options={
                'verbose_name': 'ابن/ابنة',
                'verbose_name_plural': 'الأبناء',
            },
        ),
        migrations.CreateModel(
            name='Wife',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الزوجة')),
                ('national_id', models.CharField(max_length=9, validators=[django.core.validators.RegexValidator(message='رقم الهوية يجب أن يكون 9 أرقام', regex='^\\d{9}$')], verbose_name='رقم هوية الزوجة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('guardian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wives', to='basic_data.guardian', verbose_name='ولي الأمر')),
            ],
            options={
                'verbose_name': 'زوجة',
                'verbose_name_plural': 'الزوجات',
                'unique_together': {('guardian', 'national_id')},
            },
        ),
    ]
