# Generated by Django 5.2.1 on 2025-05-28 19:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='district',
            name='representative_id',
        ),
        migrations.AddField(
            model_name='district',
            name='representative_phone',
            field=models.CharField(blank=True, help_text='أدخل رقم جوال مندوب الحي (مثال: 0599123456)', max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='رقم الجوال غير صحيح', regex='^(\\+970|0)?5[0-9]{8}$')], verbose_name='رقم جوال مندوب الحي'),
        ),
    ]
