# Generated by Django 5.2.1 on 2025-05-28 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_data', '0002_change_representative_id_to_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='gender',
            field=models.CharField(choices=[('ذكر', 'ذكر'), ('أنثى', 'أنثى')], max_length=10, verbose_name='الجنس'),
        ),
        migrations.AlterField(
            model_name='guardian',
            name='gender',
            field=models.CharField(choices=[('ذكر', 'ذكر'), ('أنثى', 'أنثى')], max_length=10, verbose_name='الجنس'),
        ),
        migrations.AlterField(
            model_name='guardian',
            name='marital_status',
            field=models.CharField(choices=[('متزوج', 'متزوج'), ('أرمل', 'أرمل'), ('مطلق', 'مطلق'), ('أعزب', 'أعزب')], max_length=20, verbose_name='الحالة الاجتماعية'),
        ),
        migrations.AlterField(
            model_name='guardian',
            name='residence_status',
            field=models.CharField(choices=[('نازح', 'نازح'), ('مقيم', 'مقيم')], max_length=20, verbose_name='حالة الإقامة'),
        ),
    ]
