# Generated by Django 5.2.1 on 2025-05-28 21:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_data', '0003_alter_child_gender_alter_guardian_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wife',
            name='national_id',
            field=models.CharField(blank=True, max_length=9, null=True, validators=[django.core.validators.RegexValidator(message='رقم الهوية يجب أن يكون 9 أرقام', regex='^\\d{9}$')], verbose_name='رقم هوية الزوجة'),
        ),
    ]
