# Generated by Django 5.2.1 on 2025-05-28 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_data', '0004_alter_wife_national_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wife',
            unique_together=set(),
        ),
    ]
