# Generated by Django 5.2.1 on 2025-06-05 13:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_data', '0005_alter_wife_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='national_id',
            field=models.CharField(blank=True, max_length=9, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='رقم الهوية يجب أن يكون 9 أرقام', regex='^\\d{9}$')], verbose_name='رقم الهوية'),
        ),
    ]
