# Generated by Django 5.2.1 on 2025-06-05 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_data', '0006_make_child_national_id_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='female_siblings_count',
            field=models.PositiveIntegerField(default=0, verbose_name='عدد الأخوة الإناث'),
        ),
        migrations.AddField(
            model_name='child',
            name='male_siblings_count',
            field=models.PositiveIntegerField(default=0, verbose_name='عدد الأخوة الذكور'),
        ),
    ]
