# Generated by Django 5.2.1 on 2025-06-06 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_data', '0007_child_female_siblings_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child',
            name='female_siblings_count',
        ),
        migrations.RemoveField(
            model_name='child',
            name='male_siblings_count',
        ),
    ]
