# Generated by Django 5.2.1 on 2025-06-21 20:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_data', '0011_guardian_housing_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='child',
            options={'ordering': ['name'], 'verbose_name': 'ابن/ابنة', 'verbose_name_plural': 'الأبناء'},
        ),
        migrations.AlterModelOptions(
            name='wife',
            options={'ordering': ['name'], 'verbose_name': 'زوجة', 'verbose_name_plural': 'الزوجات'},
        ),
        migrations.CreateModel(
            name='CitizenRegistrationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='الاسم الكامل')),
                ('national_id', models.CharField(max_length=9, unique=True, verbose_name='رقم الهوية')),
                ('phone_number', models.CharField(max_length=15, verbose_name='رقم الجوال')),
                ('gender', models.CharField(choices=[('ذكر', 'ذكر'), ('أنثى', 'أنثى')], max_length=10, verbose_name='الجنس')),
                ('current_job', models.CharField(blank=True, max_length=100, null=True, verbose_name='المهنة الحالية')),
                ('children_count', models.PositiveIntegerField(default=0, verbose_name='عدد الأطفال')),
                ('marital_status', models.CharField(choices=[('أعزب', 'أعزب'), ('متزوج', 'متزوج'), ('مطلق', 'مطلق'), ('أرمل', 'أرمل')], max_length=20, verbose_name='الحالة الاجتماعية')),
                ('wives_count', models.PositiveIntegerField(default=0, verbose_name='عدد الزوجات')),
                ('residence_status', models.CharField(choices=[('مقيم', 'مقيم'), ('نازح', 'نازح'), ('لاجئ', 'لاجئ')], max_length=20, verbose_name='حالة الإقامة')),
                ('original_governorate', models.CharField(blank=True, max_length=50, null=True, verbose_name='المحافظة الأصلية')),
                ('original_city', models.CharField(blank=True, max_length=50, null=True, verbose_name='المدينة الأصلية')),
                ('displacement_address', models.TextField(blank=True, null=True, verbose_name='عنوان النزوح')),
                ('housing_type', models.CharField(blank=True, choices=[('ملك', 'ملك'), ('إيجار', 'إيجار'), ('مستأجر', 'مستأجر'), ('مع أقارب', 'مع أقارب'), ('مخيم', 'مخيم'), ('خيمة', 'خيمة'), ('مدرسة', 'مدرسة'), ('مستشفى', 'مستشفى'), ('مسجد', 'مسجد'), ('مخزن', 'مخزن'), ('سيارة', 'سيارة'), ('شارع', 'شارع'), ('آخر', 'آخر')], max_length=20, null=True, verbose_name='نوع السكن')),
                ('status', models.CharField(choices=[('pending', 'في الانتظار'), ('approved', 'مقبول'), ('rejected', 'مرفوض')], default='pending', max_length=20, verbose_name='حالة الطلب')),
                ('admin_notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات الإدارة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الطلب')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ القبول')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='تم القبول بواسطة')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='basic_data.district', verbose_name='الحي')),
            ],
            options={
                'verbose_name': 'طلب تسجيل مواطن',
                'verbose_name_plural': 'طلبات تسجيل المواطنين',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CitizenRequestChild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الطفل')),
                ('national_id', models.CharField(blank=True, max_length=9, null=True, verbose_name='رقم الهوية')),
                ('birth_date', models.DateField(verbose_name='تاريخ الميلاد')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='basic_data.citizenregistrationrequest', verbose_name='طلب التسجيل')),
            ],
            options={
                'verbose_name': 'طفل في طلب التسجيل',
                'verbose_name_plural': 'أطفال في طلبات التسجيل',
            },
        ),
        migrations.CreateModel(
            name='CitizenRequestWife',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الزوجة')),
                ('national_id', models.CharField(blank=True, max_length=9, null=True, verbose_name='رقم الهوية')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wives', to='basic_data.citizenregistrationrequest', verbose_name='طلب التسجيل')),
            ],
            options={
                'verbose_name': 'زوجة في طلب التسجيل',
                'verbose_name_plural': 'زوجات في طلبات التسجيل',
            },
        ),
    ]
