# Generated by Django 5.2.1 on 2025-06-27 22:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_data', '0012_alter_child_options_alter_wife_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='citizenregistrationrequest',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الرفض'),
        ),
        migrations.AddField(
            model_name='citizenregistrationrequest',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_requests', to=settings.AUTH_USER_MODEL, verbose_name='تم الرفض بواسطة'),
        ),
    ]
