# Generated by Django 5.2.1 on 2025-05-28 06:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('basic_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Injured',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='أدخل الاسم الرباعي للجريح', max_length=100, verbose_name='اسم الجريح')),
                ('national_id', models.CharField(help_text='أدخل رقم الهوية (9 أرقام)', max_length=9, unique=True, validators=[django.core.validators.RegexValidator(message='رقم الهوية يجب أن يكون 9 أرقام', regex='^\\d{9}$')], verbose_name='رقم هوية الجريح')),
                ('guardian_national_id', models.CharField(help_text='أدخل رقم هوية ولي الأمر (9 أرقام)', max_length=9, validators=[django.core.validators.RegexValidator(message='رقم الهوية يجب أن يكون 9 أرقام', regex='^\\d{9}$')], verbose_name='رقم هوية ولي الأمر')),
                ('guardian_name', models.CharField(blank=True, help_text='يعبأ تلقائياً من البيانات الأساسية', max_length=100, verbose_name='اسم ولي الأمر')),
                ('phone_number', models.CharField(help_text='يقرأ من البيانات الأساسية أو يكتب يدوياً', max_length=15, validators=[django.core.validators.RegexValidator(message='رقم الجوال غير صحيح', regex='^(\\+970|0)?5[0-9]{8}$')], verbose_name='رقم الجوال')),
                ('injury_date', models.DateField(verbose_name='تاريخ الإصابة')),
                ('injury_type', models.CharField(choices=[('gunshot', 'إصابة بالرصاص'), ('shrapnel', 'إصابة بالشظايا'), ('explosion', 'إصابة بالانفجار'), ('burn', 'حروق'), ('fracture', 'كسور'), ('amputation', 'بتر'), ('other', 'أخرى')], max_length=20, verbose_name='نوع الإصابة')),
                ('injury_description', models.TextField(blank=True, help_text='تفاصيل إضافية عن الإصابة', null=True, verbose_name='وصف الإصابة')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('district', models.ForeignKey(blank=True, help_text='يقرأ تلقائياً من البيانات الأساسية', null=True, on_delete=django.db.models.deletion.SET_NULL, to='basic_data.district', verbose_name='الحي')),
                ('guardian', models.ForeignKey(blank=True, help_text='سيتم ملؤه تلقائياً عند إدخال رقم الهوية', null=True, on_delete=django.db.models.deletion.SET_NULL, to='basic_data.guardian', verbose_name='ولي الأمر')),
            ],
            options={
                'verbose_name': 'جريح',
                'verbose_name_plural': 'الجرحى',
                'ordering': ['-injury_date', 'name'],
            },
        ),
    ]
