# Generated by Django 5.2.1 on 2025-05-28 06:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('basic_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Damage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guardian_national_id', models.CharField(help_text='أدخل رقم هوية ولي الأمر (9 أرقام)', max_length=9, validators=[django.core.validators.RegexValidator(message='رقم الهوية يجب أن يكون 9 أرقام', regex='^\\d{9}$')], verbose_name='رقم الهوية')),
                ('guardian_name', models.CharField(blank=True, help_text='يقرأ تلقائياً من جدول البيانات الأساسية', max_length=100, verbose_name='اسم ولي الأمر')),
                ('phone_number', models.CharField(help_text='يقرأ من البيانات الأساسية أو يكتب يدوياً', max_length=15, validators=[django.core.validators.RegexValidator(message='رقم الجوال غير صحيح', regex='^(\\+970|0)?5[0-9]{8}$')], verbose_name='رقم الجوال')),
                ('ownership_type', models.CharField(choices=[('owned', 'ملك'), ('rented', 'إيجار')], max_length=10, verbose_name='ملك/إيجار')),
                ('housing_type', models.CharField(choices=[('apartment', 'شقة'), ('house', 'بيت'), ('villa', 'فيلا'), ('room', 'غرفة'), ('shop', 'محل تجاري'), ('warehouse', 'مستودع'), ('other', 'أخرى')], max_length=20, verbose_name='نوع الوحدة السكنية')),
                ('housing_condition', models.CharField(choices=[('excellent', 'ممتازة'), ('good', 'جيدة'), ('fair', 'متوسطة'), ('poor', 'سيئة'), ('destroyed', 'مدمرة')], max_length=20, verbose_name='حالة الوحدة السكنية')),
                ('construction_type', models.CharField(choices=[('concrete', 'باطون'), ('asbestos', 'اسبست'), ('mixed', 'مختلط')], max_length=20, verbose_name='نوع البناء')),
                ('floors_count', models.PositiveIntegerField(help_text='أدخل عدد الطوابق', verbose_name='عدد الطوابق')),
                ('damage_type', models.CharField(choices=[('total', 'كلي'), ('partial', 'جزئي')], max_length=10, verbose_name='نوع الضرر')),
                ('damage_percentage', models.PositiveIntegerField(help_text='أدخل النسبة من 0 إلى 100', verbose_name='نسبة الضرر (%)')),
                ('damage_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الضرر')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('district', models.ForeignKey(blank=True, help_text='يقرأ تلقائياً من البيانات الأساسية', null=True, on_delete=django.db.models.deletion.SET_NULL, to='basic_data.district', verbose_name='الحي')),
                ('guardian', models.ForeignKey(blank=True, help_text='سيتم ملؤه تلقائياً عند إدخال رقم الهوية', null=True, on_delete=django.db.models.deletion.SET_NULL, to='basic_data.guardian', verbose_name='ولي الأمر')),
            ],
            options={
                'verbose_name': 'ضرر',
                'verbose_name_plural': 'الأضرار',
                'ordering': ['-damage_percentage', 'guardian_name'],
            },
        ),
    ]
