# Generated by Django 5.2.1 on 2025-05-29 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('damages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='damage',
            name='estimated_cost_ils',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='أدخل التكلفة المقدرة بالشيكل', max_digits=12, null=True, verbose_name='التكلفة المقدرة (شيكل)'),
        ),
        migrations.AddField(
            model_name='damage',
            name='estimated_cost_usd',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='أدخل التكلفة المقدرة بالدولار', max_digits=12, null=True, verbose_name='التكلفة المقدرة (دولار)'),
        ),
    ]
