# Generated by Django 5.2.1 on 2025-05-28 06:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('basic_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Martyr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='أدخل الاسم الرباعي للشهيد', max_length=100, verbose_name='اسم الشهيد')),
                ('national_id', models.CharField(help_text='أدخل رقم الهوية (9 أرقام)', max_length=9, unique=True, validators=[django.core.validators.RegexValidator(message='رقم الهوية يجب أن يكون 9 أرقام', regex='^\\d{9}$')], verbose_name='رقم هوية الشهيد')),
                ('martyrdom_date', models.DateField(verbose_name='تاريخ الاستشهاد')),
                ('agent_name', models.CharField(help_text='اسم الشخص المسؤول عن شؤون الشهيد', max_length=100, verbose_name='وكيل الشهيد')),
                ('agent_national_id', models.CharField(help_text='أدخل رقم هوية الوكيل (9 أرقام)', max_length=9, validators=[django.core.validators.RegexValidator(message='رقم الهوية يجب أن يكون 9 أرقام', regex='^\\d{9}$')], verbose_name='رقم هوية الوكيل')),
                ('agent_phone', models.CharField(help_text='مثال: 0599123456', max_length=15, validators=[django.core.validators.RegexValidator(message='رقم الجوال غير صحيح', regex='^(\\+970|0)?5[0-9]{8}$')], verbose_name='رقم جوال الوكيل')),
                ('relationship_to_martyr', models.CharField(choices=[('father', 'والد'), ('mother', 'والدة'), ('brother', 'أخ'), ('sister', 'أخت'), ('son', 'ابن'), ('daughter', 'ابنة'), ('uncle', 'عم'), ('aunt', 'عمة'), ('cousin', 'ابن عم'), ('other', 'أخرى')], max_length=20, verbose_name='صلة القرابة بالشهيد')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='basic_data.district', verbose_name='الحي')),
            ],
            options={
                'verbose_name': 'شهيد',
                'verbose_name_plural': 'الشهداء',
                'ordering': ['-martyrdom_date', 'name'],
            },
        ),
    ]
