# Generated by Django 5.2.1 on 2025-06-05 21:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('martyrs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='martyr',
            name='agent_name',
            field=models.CharField(blank=True, help_text='اسم الشخص المسؤول عن شؤون الشهيد', max_length=100, null=True, verbose_name='وكيل الشهيد'),
        ),
        migrations.AlterField(
            model_name='martyr',
            name='agent_national_id',
            field=models.CharField(blank=True, help_text='أدخل رقم هوية الوكيل (9 أرقام)', max_length=9, null=True, validators=[django.core.validators.RegexValidator(message='رقم الهوية يجب أن يكون 9 أرقام', regex='^\\d{9}$')], verbose_name='رقم هوية الوكيل'),
        ),
        migrations.AlterField(
            model_name='martyr',
            name='agent_phone',
            field=models.CharField(blank=True, help_text='مثال: 0599123456', max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='رقم الجوال غير صحيح', regex='^(\\+970|0)?5[0-9]{8}$')], verbose_name='رقم جوال الوكيل'),
        ),
        migrations.AlterField(
            model_name='martyr',
            name='martyrdom_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ الاستشهاد'),
        ),
        migrations.AlterField(
            model_name='martyr',
            name='relationship_to_martyr',
            field=models.CharField(blank=True, help_text='مثل: والد، أخ، ابن، عم...', max_length=50, null=True, verbose_name='صلة القرابة بالشهيد'),
        ),
    ]
