# Generated by Django 5.2.1 on 2025-05-29 20:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('basic_data', '0005_alter_wife_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assistance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_id', models.CharField(help_text='رقم هوية المستفيد (يقبل التكرار)', max_length=9, verbose_name='رقم الهوية')),
                ('beneficiary_name', models.CharField(help_text='يتم ملؤه تلقائياً من قاعدة البيانات أو يُدخل يدوياً', max_length=200, verbose_name='اسم المستفيد')),
                ('assistance_type', models.CharField(choices=[('food', 'مساعدات غذائية'), ('money', 'مساعدات مالية'), ('medical', 'مساعدات طبية'), ('clothes', 'مساعدات كسوة'), ('shelter', 'مساعدات سكن'), ('education', 'مساعدات تعليمية'), ('fuel', 'مساعدات وقود'), ('blankets', 'أغطية ومفارش'), ('hygiene', 'مواد نظافة'), ('baby_supplies', 'مستلزمات أطفال'), ('emergency', 'مساعدات طوارئ'), ('other', 'أخرى')], max_length=50, verbose_name='نوع المساعدة')),
                ('quantity', models.DecimalField(decimal_places=2, help_text='الكمية أو المبلغ', max_digits=10, verbose_name='الكمية')),
                ('assistance_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ المساعدة')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('district_name', models.CharField(blank=True, help_text='يتم نسخه من بيانات ولي الأمر', max_length=200, null=True, verbose_name='الحي')),
                ('family_members_count', models.PositiveIntegerField(default=0, help_text='يتم نسخه من بيانات ولي الأمر', verbose_name='عدد أفراد العائلة')),
                ('guardian', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistance_records', to='basic_data.guardian', verbose_name='ولي الأمر')),
            ],
            options={
                'verbose_name': 'مساعدة',
                'verbose_name_plural': 'المساعدات',
                'ordering': ['-assistance_date', '-created_at'],
            },
        ),
    ]
