# Generated by Django 5.2.1 on 2025-05-29 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assistance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='assistance',
            table='assistance',
        ),
    ]
