# Generated by Django 5.2.1 on 2025-06-05 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistance', '0002_alter_assistance_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistance',
            name='assistance_type',
            field=models.CharField(help_text='نوع المساعدة (يمكن الكتابة بحرية)', max_length=100, verbose_name='نوع المساعدة'),
        ),
    ]
