# Generated by Django 5.2.1 on 2025-05-28 06:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('basic_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orphan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='أدخل الاسم الرباعي لليتيم', max_length=100, verbose_name='اسم اليتيم')),
                ('national_id', models.CharField(help_text='أدخل رقم الهوية (9 أرقام)', max_length=9, unique=True, validators=[django.core.validators.RegexValidator(message='رقم الهوية يجب أن يكون 9 أرقام', regex='^\\d{9}$')], verbose_name='رقم هوية اليتيم')),
                ('gender', models.CharField(choices=[('M', 'ذكر'), ('F', 'أنثى')], max_length=1, verbose_name='الجنس')),
                ('birth_date', models.DateField(verbose_name='تاريخ الميلاد')),
                ('health_status', models.CharField(choices=[('excellent', 'ممتازة'), ('good', 'جيدة'), ('fair', 'متوسطة'), ('poor', 'سيئة'), ('chronic', 'مرض مزمن'), ('disabled', 'إعاقة')], max_length=20, verbose_name='الحالة الصحية')),
                ('education_level', models.CharField(choices=[('kindergarten', 'روضة'), ('elementary', 'ابتدائي'), ('middle', 'إعدادي'), ('high', 'ثانوي'), ('university', 'جامعي'), ('graduated', 'متخرج'), ('not_enrolled', 'غير ملتحق')], max_length=20, verbose_name='المرحلة الدراسية')),
                ('deceased_national_id', models.CharField(help_text='أدخل رقم هوية الشهيد/المتوفي (9 أرقام)', max_length=9, validators=[django.core.validators.RegexValidator(message='رقم الهوية يجب أن يكون 9 أرقام', regex='^\\d{9}$')], verbose_name='رقم هوية الشهيد/المتوفي')),
                ('deceased_name', models.CharField(max_length=100, verbose_name='اسم الشهيد/المتوفي')),
                ('male_siblings_count', models.PositiveIntegerField(default=0, verbose_name='عدد الأخوة الذكور')),
                ('female_siblings_count', models.PositiveIntegerField(default=0, verbose_name='عدد الأخوة الإناث')),
                ('guardian_name', models.CharField(max_length=100, verbose_name='اسم الوصي على الأيتام')),
                ('guardian_relationship', models.CharField(choices=[('grandfather', 'جد'), ('grandmother', 'جدة'), ('uncle', 'عم'), ('aunt', 'عمة'), ('maternal_uncle', 'خال'), ('maternal_aunt', 'خالة'), ('brother', 'أخ'), ('sister', 'أخت'), ('cousin', 'ابن عم'), ('other', 'أخرى')], max_length=20, verbose_name='صلة قرابة الوصي بالأيتام')),
                ('phone_number', models.CharField(help_text='رقم جوال الوصي', max_length=15, validators=[django.core.validators.RegexValidator(message='رقم الجوال غير صحيح', regex='^(\\+970|0)?5[0-9]{8}$')], verbose_name='رقم الجوال')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='basic_data.district', verbose_name='الحي')),
            ],
            options={
                'verbose_name': 'يتيم',
                'verbose_name_plural': 'الأيتام',
                'ordering': ['name'],
            },
        ),
    ]
