# Generated by Django 5.2.1 on 2025-05-28 06:22

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('basic_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AidType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='مثال: أرز، دقيق، دواء، ملابس', max_length=100, verbose_name='اسم نوع المساعدة')),
                ('category', models.CharField(choices=[('food', 'مواد غذائية'), ('medical', 'مساعدات طبية'), ('clothing', 'ملابس'), ('shelter', 'مأوى'), ('cash', 'مساعدات نقدية'), ('education', 'مساعدات تعليمية'), ('other', 'أخرى')], max_length=20, verbose_name='فئة المساعدة')),
                ('unit', models.CharField(choices=[('kg', 'كيلوغرام'), ('piece', 'قطعة'), ('box', 'صندوق'), ('bag', 'كيس'), ('bottle', 'زجاجة'), ('package', 'عبوة'), ('liter', 'لتر'), ('meter', 'متر'), ('set', 'طقم'), ('unit', 'وحدة')], max_length=20, verbose_name='وحدة القياس')),
                ('description', models.TextField(blank=True, null=True, verbose_name='وصف المساعدة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'نوع مساعدة',
                'verbose_name_plural': 'أنواع المساعدات',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AidBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='مثال: دفعة رمضان 2024، مساعدات الشتاء', max_length=200, verbose_name='اسم الدفعة')),
                ('description', models.TextField(blank=True, null=True, verbose_name='وصف الدفعة')),
                ('start_date', models.DateField(verbose_name='تاريخ البداية')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاريخ النهاية')),
                ('status', models.CharField(choices=[('planned', 'مخطط'), ('in_progress', 'قيد التنفيذ'), ('completed', 'مكتمل'), ('cancelled', 'ملغي')], default='planned', max_length=20, verbose_name='حالة الدفعة')),
                ('total_beneficiaries', models.PositiveIntegerField(default=0, verbose_name='إجمالي المستفيدين')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('target_districts', models.ManyToManyField(blank=True, to='basic_data.district', verbose_name='الأحياء المستهدفة')),
            ],
            options={
                'verbose_name': 'دفعة مساعدات',
                'verbose_name_plural': 'دفعات المساعدات',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='AidDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distribution_date', models.DateField(verbose_name='تاريخ المساعدة')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('is_transferred', models.BooleanField(default=False, verbose_name='تم الترحيل للمستفيدين')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('guardian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distributions', to='basic_data.guardian', verbose_name='ولي الأمر')),
                ('aid_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aids.aidtype', verbose_name='نوع المساعدة')),
            ],
            options={
                'verbose_name': 'توزيع مساعدة',
                'verbose_name_plural': 'بيانات التوزيع',
                'ordering': ['-distribution_date'],
            },
        ),
        migrations.CreateModel(
            name='AidRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(choices=[('low', 'منخفضة'), ('medium', 'متوسطة'), ('high', 'عالية'), ('urgent', 'عاجلة')], default='medium', max_length=10, verbose_name='الأولوية')),
                ('status', models.CharField(choices=[('pending', 'في الانتظار'), ('approved', 'موافق عليه'), ('rejected', 'مرفوض'), ('fulfilled', 'تم التنفيذ')], default='pending', max_length=10, verbose_name='حالة الطلب')),
                ('reason', models.TextField(help_text='اشرح سبب الحاجة لهذه المساعدة', verbose_name='سبب الطلب')),
                ('request_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الطلب')),
                ('response_date', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الرد')),
                ('response_notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات الرد')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('guardian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aid_requests', to='basic_data.guardian', verbose_name='ولي الأمر')),
                ('aid_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aids.aidtype', verbose_name='نوع المساعدة المطلوبة')),
            ],
            options={
                'verbose_name': 'طلب مساعدة',
                'verbose_name_plural': 'طلبات المساعدة',
                'ordering': ['-request_date'],
            },
        ),
        migrations.CreateModel(
            name='AidBeneficiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aid_date', models.DateField(verbose_name='تاريخ المساعدة')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('guardian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aid_benefits', to='basic_data.guardian', verbose_name='ولي الأمر المستفيد')),
                ('aid_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aids.aidtype', verbose_name='نوع المساعدة')),
            ],
            options={
                'verbose_name': 'مستفيد',
                'verbose_name_plural': 'بيانات المستفيدين',
                'ordering': ['-aid_date'],
            },
        ),
        migrations.CreateModel(
            name='AidDistributionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='الكمية')),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='اختياري - للتقييم المالي', max_digits=10, verbose_name='سعر الوحدة')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الانتهاء')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('distribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='aids.aiddistribution', verbose_name='التوزيع')),
                ('aid_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aids.aidtype', verbose_name='نوع المساعدة')),
            ],
            options={
                'verbose_name': 'صنف توزيع',
                'verbose_name_plural': 'أصناف التوزيع',
                'unique_together': {('distribution', 'aid_type')},
            },
        ),
    ]
